name: Backend CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./linebot
    runs-on: ubuntu-latest
    environment: nstc-linebot-2025
    permissions:
      contents: read
      id-token: write # for OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authorize Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Who am I?
        run: |
          gcloud auth list
          gcloud config get-value account

      - name: Build and push Docker image
        run: |-
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_ID }} \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL }} \
            --memory 2Gi \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
