name: Deploy to Cloud Run

on:
  push:
    branches:
      - moe-2026

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: moe-linebot-2026
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authorize Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Who am I?
        run: |
          gcloud auth list
          gcloud config get-value account

      - name: Build Docker image locally
        run: |
          docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moe-linebot-2026/moe-linebot-2026:latest .

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Push Docker image
        run: |
          docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moe-linebot-2026/moe-linebot-2026:latest

      - name: Deploy to Cloud Run
        env:
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_SECRET_VERSION: ${{ secrets.GCP_SECRET_VERSION }}
          GOOGLE_DRIVE_ROOT_FOLDER: ${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER }}
          FIREBASE_DATA_DB: ${{ secrets.FIREBASE_DATA_DB }}
          FIREBASE_SESSION_DB: ${{ secrets.FIREBASE_SESSION_DB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
        run: |
          gcloud run deploy moe-linebot-2026 \
            --image asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moe-linebot-2026/moe-linebot-2026:latest \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL }} \
            --memory 1Gi \
            --set-env-vars LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }},LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }},GCP_SECRET_VERSION=${{ secrets.GCP_SECRET_VERSION }},GOOGLE_DRIVE_ROOT_FOLDER=${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER }},FIREBASE_DATA_DB=${{ secrets.FIREBASE_DATA_DB }},FIREBASE_SESSION_DB=${{ secrets.FIREBASE_SESSION_DB }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},OPENAI_ASSISTANT_ID=${{ secrets.OPENAI_ASSISTANT_ID }},TZ=${{ secrets.TIMEZONE }}
